name: build

on:
  push:
    branches:
      - "main"

jobs:
  build-devcontainer:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/bunny-labs/foundry-devcontainer:latest
